language: python

os:
  - linux
env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
  - PYTHON_VERSION=3.8

install:
  - source .ci/travis.sh

script:
  - pytest --cov iraf --verbose

notifications:
  email: false
